//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContextBrowser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ContextBrowser.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a {
        ///  text-decoration: none;
        ///  color: #0077cc;
        ///}
        ///a:hover {
        ///  text-decoration: underline;
        ///}
        ///a:visited {
        ///  color: #0077cc;
        ///}
        ///table {
        ///  border-spacing: 0;
        ///  border-collapse: collapse;
        ///  padding: 5px;
        ///  border: 1px solid #a0a0a0;
        ///}
        ///table,
        ///th,
        ///td {
        ///  user-select: none;
        ///}
        ///table {
        ///  border-collapse: collapse;
        ///  width: auto;
        ///  font-family: sans-serif;
        ///}
        ///th.hover-col {
        ///  background-color: #f0f0f0;
        ///}
        ///th,
        ///td {
        ///  border: 1px solid #ccc;
        ///  padding: 6px 10px;
        ///  text-align: center;
        ///}
        ///tr:hover td {
        ///  background-color: #f0f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlProducerContentStyle {
            get {
                return ResourceManager.GetString("HtmlProducerContentStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.addEventListener(&apos;DOMContentLoaded&apos;, () =&gt; {
        /// const table = document.querySelector(&apos;table&apos;);
        /// const rows = Array.from(table.rows);
        ///
        /// rows.forEach(row =&gt; {
        ///  Array.from(row.cells).forEach((cell, colIndex) =&gt; {
        ///   cell.addEventListener(&apos;mouseenter&apos;, () =&gt; {
        ///    rows.forEach(r =&gt; {
        ///     if (r.cells[colIndex])
        ///      r.cells[colIndex].classList.add(&apos;hover-col&apos;);
        ///    });
        ///    cell.classList.add(&apos;hover-cell&apos;);
        ///   });
        ///
        ///   cell.addEventListener(&apos;mouseleave&apos;, () =&gt; {
        ///    rows.forEach(r =&gt; {
        ///     if (r.cells[c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlProducerContentStyleScript {
            get {
                return ResourceManager.GetString("HtmlProducerContentStyleScript", resourceCulture);
            }
        }
    }
}
